const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1440,height:900}}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.addInitScript({content: fs.readFileSync('sim/warp.js','utf8')});
 await p.addInitScript(()=>{ localStorage.setItem('dengame-dev','1'); });
 await p.goto('file://'+process.cwd()+'/sim/game.html'); await p.waitForTimeout(1500);
 for(let i=0;i<4;i++) await p.evaluate(()=>__advance(5000));
 await p.evaluate(()=>document.querySelectorAll(".welcomeov,.lvlup,.sos-ov").forEach(e=>e.remove()));
 const E=c=>p.evaluate(c=>__E(c),c); const r={};
 await E(`(()=>{['epic','rare','uncommon'].forEach(rk=>dropWeapon({name:'Test',traits:[]},true,rk)); giveTreat(Object.keys(TREATS)[0],3,true); invSync(); huntState().home=true; applyHome(); render(); fkTick(true); })()`);
 await p.click('[data-fkopen="bag"]'); await p.click('#fk-den [data-fkopen="stash"]'); await p.evaluate(()=>__advance(300));
 const drag=async(a,bsel)=>{ const s=await p.$(a), t=await p.$(bsel); const sb=await s.boundingBox(), tb=await t.boundingBox(); await p.mouse.move(sb.x+20,sb.y+20); await p.mouse.down(); await p.mouse.move(sb.x+40,sb.y+40,{steps:4}); await p.mouse.move(tb.x+20,tb.y+20,{steps:8}); await p.mouse.up(); await p.evaluate(()=>__advance(200)); };
 const tk = await p.$eval('.fkw .islot.full[data-iloc="b"][data-ik^="t:"]',e=>e.dataset.ik);
 await drag('.fkw .islot.full[data-iloc="b"][data-ik^="t:"]', '.fkw .islot[data-iloc="s"][data-ii="5"]');
 r.treatInStash = await E(`[invState().stash[5], invState().stashC['${tk}'], invCount('${tk}')]`);
 await drag('.fkw .islot.full[data-iloc="b"][data-ik^="w:"]', '.fkw .islot[data-iloc="s"][data-ii="6"]');
 r.wInStash = await E(`[invState().stash[6], invState().stashW.length]`);
 await drag('.fkw .islot.full[data-iloc="s"][data-ii="5"]', '.fkw .islot.empty[data-iloc="b"][data-ii="25"]');
 r.treatBack = await E(`[invState().slots[25], invCount('${tk}'), invState().stash[5]]`);
 await p.screenshot({path:'sim/i36g.png'});
 const ht = await E(`huntSection().match(/data-a="hunt-view" data-id="[a-z]+"/g)`); r.huntTabs = ht;
 console.log(JSON.stringify(r)); console.log('errs',errs.slice(0,8)); await b.close();})();
