const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1440,height:900}}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.addInitScript({content: fs.readFileSync('sim/warp.js','utf8')});
 await p.addInitScript(()=>{ localStorage.setItem('dengame-dev','1'); });
 await p.goto('file://'+process.cwd()+'/sim/game.html'); await p.waitForTimeout(1500);
 for(let i=0;i<3;i++) await p.evaluate(()=>__advance(5000));
 await p.evaluate(()=>document.querySelectorAll(".welcomeov,.lvlup,.sos-ov").forEach(e=>e.remove()));
 await p.click('[data-fkopen="bag"]'); await p.evaluate(()=>__advance(300));
 const s0 = await (await p.$('.fkw .ibag[data-ibag="0"]')).boundingBox(), s4 = await (await p.$('.fkw .ibag[data-ibag="4"]')).boundingBox();
 console.log(s0, s4);
 await p.mouse.move(s0.x+20,s0.y+20); await p.mouse.down(); await p.mouse.move(s0.x+40,s0.y+30,{steps:4});
 console.log('ghost', await p.$$eval('.ighost',e=>e.length));
 await p.mouse.move(s4.x+20,s4.y+20,{steps:6});
 console.log('at', await p.evaluate(([x,y])=>{const t=document.elementFromPoint(x,y); return t && (t.className+' | '+(t.closest('.ibag')||{}).outerHTML?.slice(0,80));},[s4.x+20,s4.y+20]));
 await p.mouse.up(); await p.evaluate(()=>__advance(200));
 console.log(await p.evaluate(()=>__E(`JSON.stringify(invState().eqB)`)));
 console.log('errs',errs); await b.close();})();
