const { chromium } = require('playwright'); const fs=require('fs');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1920,height:1080}}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.addInitScript({content: fs.readFileSync('sim/warp.js','utf8')});
 await p.addInitScript(()=>{ localStorage.setItem('dengame-dev','1'); });
 await p.goto('file://'+process.cwd()+'/sim/game.html'); await p.waitForTimeout(1200);
 for(let i=0;i<6;i++) await p.evaluate(()=>__advance(2000));
 await p.evaluate(()=>document.querySelectorAll(".welcomeov,.lvlup,.sos-ov").forEach(e=>e.remove()));
 const r={};
 r.dock = await p.$$eval('#fk-dock [data-fkopen]',e=>e.map(x=>x.dataset.fkopen));
 await p.click('[data-fkopen="hunt"]'); await p.evaluate(()=>__advance(300));
 r.zones = await p.$$eval('.fkw .zcard b',e=>e.map(x=>x.textContent));
 await p.click('[data-fkopen="@settings"]'); await p.evaluate(()=>__advance(300));
 await p.click('[data-set="uisize"][data-v="1.15"]'); await p.evaluate(()=>__advance(200));
 r.fkz = await p.evaluate(()=>__E('fkScale')); r.cred = await p.$$eval('.credlist li',e=>e.length);
 await p.screenshot({path:'sim/s40-set.png'});
 await p.click('.setov [data-close]');
 await p.evaluate(()=>__E(`huntState().home=true; applyHome(); render(); fkTick(true)`)); await p.evaluate(()=>__advance(500));
 await p.click('[data-fkopen="bag"]'); await p.evaluate(()=>__advance(300));
 await p.screenshot({path:'sim/s40-home.png'});
 console.log(JSON.stringify(r), errs); await b.close();})();
