"""Write docs/research-package/file-index.md: every research file with size, grouped by folder.
Run from the repo root: python3 tools/atlas/file_index.py"""
import os, subprocess, collections
ROOTS = ['ref', 'species', 'docs/claude', 'docs/research-package', 'docs/log', 'tools/den', 'tools/atlas']
files = subprocess.run(['git', 'ls-files', '--cached', '--others', '--exclude-standard', *ROOTS],
                       capture_output=True, text=True, check=True).stdout.split()
groups = collections.OrderedDict()
for f in sorted(files):
    groups.setdefault(os.path.dirname(f), []).append(f)
def size(f):
    n = os.path.getsize(f)
    return f'{n/1e6:.1f} MB' if n >= 1e6 else f'{n/1e3:.0f} KB' if n >= 1e3 else f'{n} B'
out = ['# Full file index (generated)', '', '[← Master index](README.md)', '',
       f'Generated by `tools/atlas/file_index.py` from git. {len(files)} files under: ' + ', '.join(f'`{r}/`' for r in ROOTS) + '.',
       'Game code (`apps/`, `sim/`, `engine/`, `archive/`, `art/`) is left out on purpose.', '']
for d, fs in groups.items():
    out += [f'## `{d}/` ({len(fs)})', '', '| File | Size |', '|---|---|']
    out += [f'| `{os.path.basename(f)}` | {size(f)} |' for f in fs] + ['']
open('docs/research-package/file-index.md', 'w').write('\n'.join(out))
print(len(files), 'files,', len(groups), 'folders')
