/* ===== Mail: letters and gifts ===== */
function mailState(){ state.mail = state.mail || []; return state.mail; }
function mailUnread(){ return mailState().filter(m => !m.read || (m.items && m.items.length && !m.claimed)).length; }
function itemLabel(it){ if (it.daily){ const g = giftFor(it.daily, giftDim(it.ym)); return [g.big ? "🎁" : "📦", "Day " + it.daily + ": " + g.label]; } if (it.meats) return ["🍖", fmtMeat(it.meats) + " meats"]; if (it.coins) return ["🪙", it.coins + " Dingo Coins"]; if (it.candy) return ["🍬", it.candy + " candy"]; if (it.bones) return ["🦴", it.bones + " bones"];
  if (it.spirit) return ["✨", it.spirit + " spirit"]; if (it.ess) return [ASP[Object.keys(it.ess)[0]] ? ASP[Object.keys(it.ess)[0]].i : "⚗️", Object.entries(it.ess).map(([k,n]) => n + " " + (ASP[k] ? ASP[k].n : k)).join(", ")];
  if (it.tome) return ["📖", tomeName(it.tome)]; if (it.treat) return [TREATS[it.treat] ? TREATS[it.treat].i : "🍬", (it.n || 1) + "× " + (TREATS[it.treat] ? TREATS[it.treat].n : it.treat)]; if (it.brew) return ["🧪", potName(it.brew.slice(0,-1), +it.brew.slice(-1))];
  if (it.weapon) return [it.weapon.icon || "⚔️", it.weapon.name]; if (it.pup) return ["🐾", it.pup.nick || pupName(it.pup)]; if (it.starterPup) return ["🐶", "A starter pup"]; if (it.blessing) return ["✨", "Blessings: " + it.blessing.map(t => POT_TYPES[t].name).join(" + ") + " (" + (it.mins||30) + " min)"]; if (it.bandana) return ["🎀", (BANDANAS[it.bandana] ? BANDANAS[it.bandana][0] : "New") + " bandana"]; return ["🎁","A gift"]; }
function claimMail(id){ const m = mailState().find(x => x.id === id); if (!m || m.claimed) return; const H = huntState(), K = packState();
  (m.items || []).forEach(it => { if (it.daily){ claimGift(it.daily, it.ym); return; } if (it.meats) H.meats += it.meats; if (it.coins) shopState().coins += it.coins; if (it.candy) addEvCur(it.candy); if (it.bones) earn(it.bones); if (it.spirit) K.spirit = (K.spirit||0) + it.spirit;
    if (it.ess) Object.entries(it.ess).forEach(([k,n]) => addEss(k, n)); if (it.tome) giveTome(it.tome, true); if (it.treat) giveTreat(it.treat, it.n || 1, true); if (it.brew){ const B2 = boostState(); B2.inv[it.brew] = (B2.inv[it.brew]||0) + 1; }
    if (it.weapon){ const w = Object.assign({}, it.weapon, {id: uid()}); ensureTraits(w); H.weapons.push(w); } if (it.pup){ K.pups.push(Object.assign({}, it.pup, {id: uid()})); } if (it.bandana) giveBandana(it.bandana); if (it.blessing){ const B2 = boostState(); it.blessing.forEach(t => { if (POT_TYPES[t]) brewStatus(t, 0, (it.mins || 30)*60000); }); toast("💛 Blessings are working: " + it.blessing.map(t => potName(t, 0)).join(" and ") + "!"); } if (it.starterPup){ const p = hatchOne({pool:[["goodpup","common",1]], mult:1, lvl:1}); K.pups.push(p); if (K.autoEquip) packAutoEquip(); setTimeout(() => showHatchFx([p], "💌"), 300); } });
  m.claimed = true; m.read = true; syncGhosts(); syncPups(); sfx("chest"); toast("📬 Gifts accepted! 🐾"); }
function openMail(){ fkOpen("@mail", true); }

