// node tools/bench/probe/fox_vs_wolf_chart.mjs out.png : small multiples, one per joint: measured dogs (Catavitello 2015 walk, mean ±1 SD band),
// our wolf (hero3) and GrumpyDingo's tracked fox, each over one stride from that leg's touchdown. Palette: dataviz reference slots 1-3.
import fs from 'node:fs'; import { execFileSync } from 'node:child_process'; import { createRequire } from 'node:module';
const tmp = fs.mkdtempSync('/tmp/claude-0/-home-user-Dog/3ff36a2a-418a-5e21-b2aa-c610e4c0c5f5/scratchpad/fvw-');
execFileSync('node', ['tools/bench/probe/fox_vs_wolf.mjs', '--json', tmp + '/d.json']); const O = JSON.parse(fs.readFileSync(tmp + '/d.json', 'utf8'));
const ref = {}; for (const l of fs.readFileSync('ref/research/fetched/04-gait-curves/curves.csv', 'utf8').split('\n').slice(1)) { const c = l.split(','); if (c[0] === 'catavitello2015_retrievers' && c[1] === 'walk') (ref[c[2]] ||= [])[+c[3]] = [+c[4], +c[5]]; }
const C = { dog: '#2a78d6', wolf: '#eb6834', fox: '#1baf7a', ink: '#0b0b0b', ink2: '#52514e', muted: '#898781', grid: '#e1e0d9', base: '#c3c2b7', surf: '#fcfcfb' };
const J = [['shoulder', 'Shoulder', 'fore'], ['elbow', 'Elbow', 'fore'], ['carpus', 'Wrist (carpus)', 'fore'], ['stifle', 'Knee (stifle)', 'hind'], ['tarsus', 'Hock (tarsus)', 'hind']];
const W = 330, H = 230, m = { l: 40, r: 12, t: 30, b: 34 }; let cells = '';
for (const [k, name, leg] of J) { const d = ref[k], wolf = O.wolf[k], fox = O.fox[k] || [], n = d.length - 1;
  const all = [...d.flatMap(e => [e[0] - e[1], e[0] + e[1]]), ...wolf, ...fox.map(e => e[1])], lo = Math.floor(Math.min(...all) / 20) * 20, hi = Math.ceil(Math.max(...all) / 20) * 20;
  const X = u => m.l + u * (W - m.l - m.r), Y = v => m.t + (hi - v) / (hi - lo) * (H - m.t - m.b), path = P => P.map((p, i) => (i ? 'L' : 'M') + X(p[0]).toFixed(1) + ' ' + Y(p[1]).toFixed(1)).join('');
  const duty = leg === 'fore' ? O.duty.wolfFore : O.duty.wolfHind; let g = `<rect x="${X(0)}" y="${m.t}" width="${X(duty) - X(0)}" height="${H - m.t - m.b}" fill="#f1f0eb"/><text x="${X(duty / 2)}" y="${m.t + 11}" font-size="10" fill="${C.muted}" text-anchor="middle">paw down</text><text x="${X((1 + duty) / 2)}" y="${m.t + 11}" font-size="10" fill="${C.muted}" text-anchor="middle">swing</text>`;
  for (let v = lo; v <= hi; v += 20) g += `<line x1="${m.l}" x2="${W - m.r}" y1="${Y(v)}" y2="${Y(v)}" stroke="${C.grid}" stroke-width="1"/><text x="${m.l - 5}" y="${Y(v) + 3.5}" font-size="10" fill="${C.muted}" text-anchor="end">${v}°</text>`;
  if (lo <= 180 && hi >= 180) g += `<line x1="${m.l}" x2="${W - m.r}" y1="${Y(180)}" y2="${Y(180)}" stroke="${C.base}" stroke-dasharray="3 3"/><text x="${W - m.r}" y="${Y(180) - 3}" font-size="9" fill="${C.muted}" text-anchor="end">straight</text>`;
  for (const p of [0, .25, .5, .75, 1]) g += `<text x="${X(p)}" y="${H - m.b + 14}" font-size="10" fill="${C.muted}" text-anchor="middle">${p * 100}%</text>`;
  const band = [...d.map((e, i) => [i / n, e[0] + e[1]]), ...d.map((e, i) => [i / n, e[0] - e[1]]).reverse()];
  g += `<path d="${path(band)}Z" fill="${C.dog}" opacity=".14"/><path d="${path(d.map((e, i) => [i / n, e[0]]))}" fill="none" stroke="${C.dog}" stroke-width="2"/>`;
  g += `<path d="${path(wolf.map((v, i) => [i / 100, v]))}" fill="none" stroke="${C.wolf}" stroke-width="2"/>`;
  if (fox.length) g += `<path d="${path(fox)}" fill="none" stroke="${C.fox}" stroke-width="2"/>` + fox.map(e => `<circle cx="${X(e[0])}" cy="${Y(e[1])}" r="2.6" fill="${C.fox}" stroke="${C.surf}" stroke-width="1.5"/>`).join('');
  const st = O.joints[k]; g += `<text x="${m.l}" y="16" font-size="13" font-weight="600" fill="${C.ink}">${name}</text>`;
  cells += `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="Inter,system-ui,sans-serif">${g}</svg>`; }
const leg = `<div style="display:flex;gap:18px;align-items:center;font:13px system-ui;color:${C.ink2};margin:4px 0 8px"><span><i style="display:inline-block;width:18px;height:3px;background:${C.dog};vertical-align:middle"></i> real dogs walking (5 retrievers, mean; band ±1 SD)</span><span><i style="display:inline-block;width:18px;height:3px;background:${C.wolf};vertical-align:middle"></i> our wolf</span><span><i style="display:inline-block;width:18px;height:3px;background:${C.fox};vertical-align:middle"></i> your fox (hand-tracked, one stride)</span></div>`;
fs.writeFileSync(tmp + '/c.html', `<body style="margin:0;padding:12px 14px;background:${C.surf};font-family:system-ui"><div style="font:600 16px system-ui;color:${C.ink}">Joint angles over one stride, from that paw's touchdown (180° = straight)</div><div style="font:12px system-ui;color:${C.ink2};margin-top:2px">The dogs' wrist is measured to the toe tip, so their paw-down wrist reads 20-35° high. Fox hock and shoulder sit 40-60° off both: likely where the points were clicked.</div>${leg}<div style="display:grid;grid-template-columns:repeat(3,${W}px);gap:6px 10px">${cells}</div>`);
const { chromium } = createRequire(process.cwd() + '/package.json')('playwright'); const br = await chromium.launch(); const p = await br.newPage({ viewport: { width: 3 * W + 50, height: 600 }, deviceScaleFactor: 2 }); await p.goto('file://' + tmp + '/c.html'); await p.screenshot({ path: process.argv[2], fullPage: true }); await br.close();
